### ISSUE TITLE
Accept command line arguments

### ISSUE THREAD

**Issue by shimoncohen** [nspitzern/Image-Process-Project#1]
In your Main, you wrote string literals for input and output images.
Best practice is to accept the image and the wanted output path as parameters to the Main from the command line (through the args parameter).

https://github.com/nspitzern/Image-Process-Project/blob/b5baa8e3b6eedf31130fa8a9a4e35e68802e766d/src/Main.java#L17
https://github.com/nspitzern/Image-Process-Project/blob/b5baa8e3b6eedf31130fa8a9a4e35e68802e766d/src/Main.java#L23

**Comment by nspitzern** [comment]
Fixed in the main
