### ISSUE TITLE
Calculating multiple times instead of using a variable

### ISSUE THREAD

**Issue by shimoncohen** [nspitzern/Image-Process-Project#2]
In multiple location in your code there are uses of the same calculations multiple times, instead of calculating once and using the result.

An example to this behavior is the following:
https://github.com/nspitzern/Image-Process-Project/blob/b5baa8e3b6eedf31130fa8a9a4e35e68802e766d/src/ImageProcess/Resize.java#L20-L22

This should become:
```java
double lowX = x / column_scaling_factor;
double lowY = y / row_scaling_factor;
r = ImageProcessMath.bilinearInterpolation(img, lowX, lowY, 0);
g = ImageProcessMath.bilinearInterpolation(img, lowX, lowY, 1);
b = ImageProcessMath.bilinearInterpolation(img, lowX, lowY, 2);
```

**Comment by nspitzern** [comment]
Fixed in Nearest -Neighbor resize and Bi-linear resize.
Also reduced calculation numbers in ImageProcessMath.
